### ISSUE TITLE
fix the html issue

### ISSUE THREAD

**Issue by YokeshwarRS** [mohd-akram/vscode-html-format#3]
Issue Type: <b>Bug</b>

created a file in html ,but its not working on that format 

Extension version: 0.0.3
VS Code version: Code 1.40.1 (8795a9889db74563ddd43eb0a897a2384129a619, 2019-11-13T16:49:35.976Z)
OS version: Windows_NT x64 10.0.18362

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-8265U CPU @ 1.60GHz (8 x 1800)|
|GPU Status|2d_canvas: enabled<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>metal: disabled_off<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>protected_video_decode: enabled<br>rasterization: enabled<br>skia_renderer: disabled_off<br>surface_control: disabled_off<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>viz_display_compositor: enabled_on<br>viz_hit_test_surface_layer: disabled_off<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|undefined|
|Memory (System)|7.89GB (2.31GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|
</details>

**Comment by mohd-akram** [comment]
Do `Ctrl + Shift + P` and select Format Document, or use `Shift + Alt + F`.

**Comment by YokeshwarRS** [comment]
No it's not working

**Comment by mohd-akram** [comment]
Can you show me the file you're using? Do you get a popup asking you which formatter to use?

**Comment by YokeshwarRS** [comment]
![Screenshot (43)](https://user-images.githubusercontent.com/57496781/69492002-9ab1a880-0ec2-11ea-9f21-a10147c3a859.png)
see its not utilizing the format

**Comment by mohd-akram** [comment]
I don't know why it says Django HTML at the bottom there. Disable any Django extension you have and reload the window.

**Comment by YokeshwarRS** [comment]
Fine but I fixed it just changing my editor selection. thank for  your suggestions😊

**Comment by mohd-akram** [comment]
Great :D
